global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
